import os

# Paths
CWD = os.path.abspath(os.path.dirname(__file__))
CONFIG_PATHS = [CWD]


# Menus
MAIN_MENU = 'MAM_MAIN_MENU'
MAIN_MENU_NAME = 'MAM Tools'
HOTKEY_MENU_NAME = 'MAM_HOTKEY_MENU_NAME'
MARKING_MENU_NAME = 'MAM_MARKING_MENU_NAME'
SETTINGS_MENU_NAME = 'MAM_SETTINGS_MENU_NAME'

# Settings
CUSTOM_SETTING_STATE = 'MAM_CUSTOM_SETTING_STATE'
INIT_SHADER_OVERRIDE_STATUS = 'MAM_INIT_SHADER_OVERRIDE_STATUS'
INIT_SHADER_OVERRIDE_MATNAME = 'mam_blinn'
INIT_SHADER_OVERRIDE_JOBNUM = 'MAM_INIT_SHADER_OVERRIDE_JOBNUM'

# Hotkeys
HOTKEY_CURRENT_SET = 'MAM_HOTKEY_CURRENT_SET'

# Marking Menus
MARKING_MENU_POPUP_NAME = 'MAM_MARKING_MENU_POPUP_NAME'

# Globals
USE_MEL, USE_PYTHON = 'mel', 'python'

